openapi: 3.0.0
info:
  title: API de Gestión de Usuarios
  description: Documentación de la API
  version: 1.0.0
servers:
  - url: http://localhost:5000

paths:
  $ref: './userSwagger.yaml'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        nombre:
          type: string
        apellido:
          type: string
        email:
          type: string
        telefono:
          type: string
        direccion:
          type: string
