/users:
  get:
    summary: Obtener lista de usuarios
    description: Devuelve todos los usuarios registrados en el sistema.
    operationId: getUsers
    responses:
      '200':
        description: Lista de usuarios
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'

/users/{id}:
  get:
    summary: Obtener un usuario por ID
    description: Devuelve un usuario basado en su ID.
    operationId: getUserById
    parameters:
      - name: id
        in: path
        required: true
        description: ID del usuario
        schema:
          type: integer
    responses:
      '200':
        description: Usuario encontrado
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      '404':
        description: Usuario no encontrado
